In [16]:
import numpy as np

In [10]:

print("==================creating array=====================")
arr = np.array([1,2,3,4])
lst = [1,2,3,4]
print("==================Add  5=====================")
print(arr+5)
print([x+5 for x in lst])
print("==================multiply by 2=====================")
print(arr*2)
print([x*2 for x in lst])
print("==================Squares=====================")
print(arr**2)
print([x**2 for x in lst])
print("==================Mean=====================")
print(np.mean(arr))
print(sum(lst)/len(lst))
print("==================Filtering factors of 2=====================")
print(arr[arr % 2 == 0])
print([x for x in lst if x%2==0])
print("==================2D Array=====================")
print(np.array([[1,2],[3,4]]))
print([[1,2],[3,4]])
print("==================Adding Two Arrays=====================")
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)

a=[1,2,3]
b=[4,5,6]
print([x+y for x,y in zip(a,b)])

print("==================Broadcasting=====================")
'''Broadcasting is a mechanism that allows arrays of different shapes to perform arithmetic operations together without 
explicitly resizing or copying data'''
print(arr+1)
#python list: Not directly supported like NumPy

print("===================Condtional Replace===============")
#Conditional Replace
arr[arr>2] = 0
print(arr)

lst = [1,2,3,4]
print([0 if x>2 else x for x in lst])


==================creating array=====================
==================Add  5=====================
[6 7 8 9]
[6, 7, 8, 9]
==================multiply by 2=====================
[2 4 6 8]
[2, 4, 6, 8]
==================Squares=====================
[ 1  4  9 16]
[1, 4, 9, 16]
==================Mean=====================
2.5
2.5
==================Filtering factors of 2=====================
[2 4]
[2, 4]
==================2D Array=====================
[[1 2]
 [3 4]]
[[1, 2], [3, 4]]
==================Adding Two Arrays=====================
[5 7 9]
[5, 7, 9]
==================Broadcasting=====================
[2 3 4 5]
===================Condtional Replace===============
[1 2 0 0]
[1, 2, 0, 0]


In [14]:
a=np.linspace(0,10,35)
a

array([ 0.        ,  0.29411765,  0.58823529,  0.88235294,  1.17647059,
        1.47058824,  1.76470588,  2.05882353,  2.35294118,  2.64705882,
        2.94117647,  3.23529412,  3.52941176,  3.82352941,  4.11764706,
        4.41176471,  4.70588235,  5.        ,  5.29411765,  5.58823529,
        5.88235294,  6.17647059,  6.47058824,  6.76470588,  7.05882353,
        7.35294118,  7.64705882,  7.94117647,  8.23529412,  8.52941176,
        8.82352941,  9.11764706,  9.41176471,  9.70588235, 10.        ])

In [19]:
'''comparing arange() and linspace()'''
a=np.arange(0,10,2)
b=np.linspace(0,10,5)
print(len(a))
print(a)
print(len(b))
print(b)

5
[0 2 4 6 8]
5
[ 0.   2.5  5.   7.5 10. ]


In [21]:
arr = np.arange(55,66)
print(arr)

[55 56 57 58 59 60 61 62 63 64 65]


In [22]:
mask = arr > 58
print(mask)

[False False False False  True  True  True  True  True  True  True]


In [23]:

filtered = arr[mask]
print(filtered)

[59 60 61 62 63 64 65]


In [24]:
#Multiple Conditions
print(arr[(arr>57) & (arr < 63)])

[58 59 60 61 62]


In [25]:
#marks example
marks = np.array([67,34,89,32])
passed_boolean = marks > 35
print(passed_boolean)
print(marks[passed_boolean])

[ True False  True False]
[67 89]


In [26]:
#shallow v/s deep copy
a=np.array([10,20,30,40,50,60])

#shallow copy
b = a[0:5]
print(a)
print(b)

b[0] = 999
print(a)
print(b)

#Deep Copy
c=a.copy()

c[1] = 888
print(a)
print(c)



[10 20 30 40 50 60]
[10 20 30 40 50]
[999  20  30  40  50  60]
[999  20  30  40  50]
[999  20  30  40  50  60]
[999 888  30  40  50  60]


In [61]:
print(np.random.randint(1,10,5))
print(np.random.randint(1,10,5))
print(np.random.rand(5))
print(np.random.rand(5))



[7 9 7 1 1]
[9 9 4 9 3]
[0.00695213 0.5107473  0.417411   0.22210781 0.11986537]
[0.33761517 0.9429097  0.32320293 0.51879062 0.70301896]


In [73]:
print("----------------------WITH SEED-------------------------------")
np.random.seed(101)
print(np.random.randint(1,10,5))
np.random.seed(42)
print(np.random.randint(1,10,5))
print(np.random.rand(5))
print(np.random.rand(5))

print(np.random.uniform(10,50,5))


----------------------WITH SEED-------------------------------
[7 4 8 5 7]
[0.44583275 0.09997492 0.45924889 0.33370861 0.14286682]
[6.50888473e-01 5.64115790e-02 7.21998772e-01 9.38552709e-01
 7.78765841e-04]
[49.68846237 34.69926039 34.46612642 10.28265221 10.922497  ]


In [12]:
import numpy as np
import pandas as pd

companies = ["TCS","Infosys","Wipro"]
sales = [100,20,300]

arr = np.array(sales)

s = pd.Series(data=sales,index=companies)
print(arr)
print(s)

print(list(range(len(arr))))
print(list(s.index))

print(arr[1])
print(s["Infosys"])

[100  20 300]
TCS        100
Infosys     20
Wipro      300
dtype: int64
[0, 1, 2]
['TCS', 'Infosys', 'Wipro']
20
20


In [23]:
#create a simple dataframe
import pandas as pd

df = pd.DataFrame({'Sales':[100,200,300],'Profit':[20,50,70]},index=['TCS','Infosys','Wipro'])
print(df)
print(df['Sales']) #Select a row using label
print(df.Sales)#Select a row using row number/id

print(df.loc['Infosys']) #Select a row using label
print(df.iloc[1]) # Select a row using row number/id


         Sales  Profit
TCS        100      20
Infosys    200      50
Wipro      300      70
TCS        100
Infosys    200
Wipro      300
Name: Sales, dtype: int64
TCS        100
Infosys    200
Wipro      300
Name: Sales, dtype: int64
Sales     200
Profit     50
Name: Infosys, dtype: int64
Sales     200
Profit     50
Name: Infosys, dtype: int64


In [24]:
print(df.loc['Infosys','Profit']) #1 row, 1 col

50


In [52]:
#loc and iloc
import pandas as pd

data={
    "Player":['Virat','Rohit','MS Dhoni'],
    "Match1":[45,55,30],
    "Match2":[67,72,40],
    "Match3":[82,60,50],
    "Match4":[82,60,50],
    "Match5":[82,60,50],
    "Match6":[82,60,50],
    "Match7":[82,60,50]
}

df = pd.DataFrame(data).set_index("Player")
print(df)

#First row
print("------------------------------First row-------------------------")

print(df.loc["Virat"].values)
print(df.iloc[0].values)

#print(df.head())

#subset
print("------------------------------Subset-------------------------")

print(df.loc[["Virat","MS Dhoni"],["Match1"]])

#slicing
print("------------------------------Slicing-------------------------")

# From Virat to Rohit (inclusive)
print(df.loc["Virat":"Rohit", "Match1":"Match3"])
# First two rows, first three columns
print(df.iloc[0:2, 0:3])

df = pd.DataFrame({"Employee" : ["Vachan","Sreenath","Nikhil", "Aashutosh","Krutik","Rohit"],
                    "Department":["IT","HR","IT","HR","Fin","FIn"],
                    "Salary": [50000,np.nan,100000,450000,50000,74000]})
print(df)

#INDEXING
print("-----------------------INDEXING----------------------")
df_indexed = df.set_index("Employee")
print(df_indexed)

#Filtering
print("-----------------Filtering-----------------")

print(df[df["Salary"] > 50000])

#Check missing
print("------------check missing------------------")

print(df.isnull())

#Fill missing
print("-----------------Fill missing-----------")
print(df.fillna(220))
print("-----------------Drop na-----------")

#Drop missing
print(df.dropna())
print("-----------------Grouping-----------")

#grouping
print(df.groupby("Department")["Salary"].mean())

print("-----------------merge-----------")

#Merge (Join)
df_bonus = pd.DataFrame({
    "Employee":["Rohit","Nikhil","Raj"],
    "Bonus":[5000,7000,4000]
})
merged = pd.merge(df, df_bonus, on="Employee")
print(merged)


merged  = pd.merge(df,df_bonus,on="Employee",how="left")
print(merged)

print("-----------------Concat-----------")

#concat

df_new = pd.DataFrame({
    "Employee":["Kiran"],
    "Department":["IT"],
    "Salary":[55000]
})

concat_df = pd.concat([df,df_new], ignore_index=True)
print(concat_df)

          Match1  Match2  Match3  Match4  Match5  Match6  Match7
Player                                                          
Virat         45      67      82      82      82      82      82
Rohit         55      72      60      60      60      60      60
MS Dhoni      30      40      50      50      50      50      50
------------------------------First row-------------------------
[45 67 82 82 82 82 82]
[45 67 82 82 82 82 82]
------------------------------Subset-------------------------
          Match1
Player          
Virat         45
MS Dhoni      30
------------------------------Slicing-------------------------
        Match1  Match2  Match3
Player                        
Virat       45      67      82
Rohit       55      72      60
        Match1  Match2  Match3
Player                        
Virat       45      67      82
Rohit       55      72      60
    Employee Department    Salary
0     Vachan         IT   50000.0
1   Sreenath         HR       NaN
2     Nikhil         

In [69]:
import pandas as pd
df = pd.read_csv("tips.csv")
print(df)
print(df.head())
print(df[df['total_bill']>20].head())
print(df[(df['total_bill']>20) & (df['tip'] < 3 )].head())
print(df.loc[df['size']==2, ['total_bill','tip']].head())

print(df.query("total_bill >20 and tip <3").head())
print(df[df['day'].isin(['Sat', 'Sun'])].head())
print(df[df['total_bill'].between(15,25)].head())
print(df[df['gender'].astype(str).str.contains("Male")].head())


     total_bill   tip  gender smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name     CC Number Payment ID  
0    Christy

In [78]:
# EDA (EXPLORATORY DATA ANALYSIS

df =pd.read_csv("tips.csv")
print(df.head())
print(df.tail())
print(df.shape)
print(df.columns)
print(df.dtypes)
print(df.info())
print(df.isnull().sum())
print(df.describe())
print(df['day'].unique())

#Total bill analysis

print(df['total_bill'].min())

print(df['total_bill'].max())

print(df['total_bill'].mean())
print(df['total_bill'].median())

print(df.groupby('day')['total_bill'].mean())
print(df.groupby('gender')['tip'].mean())

print(df.nlargest(5,'total_bill'))
print(df.nsmallest(5,'total_bill'))

print(df[df['total_bill']>30].head())
print(df[df['smoker'] == 'Yes'].head())

print(df[df['day'].isin(['Sat','Sun'])].head())

df['Tip_Percentage'] = (df['tip']/df['total_bill'])*100
print(df)

print("----------------------numpy operation--------------------------------")
#numpy operations
bill_array = np.array(df['total_bill'])
print(round(np.mean(bill_array),2))
print(round(np.median(bill_array),2))

print(np.std(bill_array))

print(df['size'].value_counts())
print(df['smoker'].value_counts())




   total_bill   tip  gender smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name     CC Number Payment ID  
0  Christy Cunningham  3.560330e+15    Sun2959  
1      Douglas Tucker  4.478070e+15    Sun4608  
2      Travis Walters  6.011810e+15    Sun4458  
3    Nathaniel Harris  4.676140e+15    Sun5260  
4        Tonya Carter  4.832730e+15    Sun2251  
     total_bill   tip  gender smoker   day    time  size  price_per_person  \
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00